resume_directory: ../data/input/example_resumes
summary_output_directory: ../data/output
data_schema_dir: ../data/schema

extractors:
 experience:
  - [Teacher, teaching, tutor]
  - [developer, software developer, software engineer, dev]
  - trader
  - [marketing head, marketing manager]
  - [data analyst]

 platforms:
  - Linux
  - Windows
  - [Mac, MacOS]

 database:
  - SQL
  - MySQL
  - [Postgress, Postgresql]
  - Oracle
  - GraphQL

 programming:
  - [java, JavaEE]
  - C
  - C++
  - C#
  - .NET
  - Matlab
  - R
  - python
  - VHDL
  - PHP
  - JavaScript
  - HTML
  - CSS
  - Go


 machinelearning:
  - [sklearn, scikit-learn, sk-learn]
  - [tensorflow, tf, tensor-flow]
  - keras
  - PyTorch
  - h20
  - [neural networks,deep learning]
  - [data science,data analysis]


 universities:
  - [TU Delft, TUDelft, Delft University of Technology]
  - [Univerity of Twente, UTwente]
  - [University of Amsterdam, UvA]
  - [Vrije Univesriteit, VU University, VU Amsterdam, VU]
  - MIT
  - [Veermata Jijabai Technological Institute,VJTI]

 languages:
  - Dutch
  - English
  - German
  - Spanish
  - [Chinese, Mandarin]

 hobbies:
  - [swimming, swim]
  - [soccer, football]
  - painting
  - reading

 open-source:
  - github
  - bitbucket
  - gitlab
  - sourceforge
  - gitkraken